title: "Ratanlal Mahanta - Computational Finance & AI"
<<<<<<< HEAD
description: "Personal website showcasing professional experience and research in quantitative finance."
theme: minima
=======
#email: "your.email@example.com"
description: "Computational Finance | AI-Driven Quantitative Research"
baseurl: "" # Leave it empty unless your site is hosted in a subfolder
url: "https://ratanlalmahanta.github.io" # Your GitHub Pages URL

# Theme settings
theme: "minimal-mistakes-jekyll"
About Me

Welcome! I'm **Ratanlal Mahanta**, a lead scientist with over 12 years of experience in computational finance, AI, and risk management. My work is deeply rooted in quantitative finance, where I bring a blend of academic rigor and practical insight into financial modeling, AI-driven solutions, and advanced risk management techniques.

My professional journey spans roles in research and consulting, with a focus on AI-integrated financial markets, option pricing models, credit valuation adjustment (CVA),FRTB, and interest rate models. I have a passion for applying novel mathematical methods to real-world challenges, especially in areas like green finance, tail risk hedging, and Bayesian machine learning. In recent years, I've been actively engaged in developing AI-driven tools to optimize portfolio selection, calibrate complex models, and enhance decision-making processes in financial markets.

Feel free to explore my GitHub for projects, presentations, and resources that reflect my dedication to pushing the boundaries of finance and AI. Thank you for visiting!

# Social media links
social_links:
  - icon: "github"
    icon_url: "https://github.com/ratanlalmahanta"
  - icon: "linkedin"
    icon_url: "https://www.linkedin.com/in/ratanlalmahanta/"
  - icon: "google-scholar"
    icon_url: "https://scholar.google.com/citations?user=SpE58EQAAAAJ&hl=en"

# Navigation menu
nav:
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Publications"
    url: "/publications/"

# Exclude files from the generated site
exclude:
  - "README.md"
>>>>>>> 9f54e573f34a0094e34b10939026e56687afb889
